name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
      use-emoji:
        description: 'Include emojis in the greeting'
        required: false
        default: false
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }} ${{ fromJSON('[\"\", \"😊\"]')[github.event.inputs['use-emoji'] == 'true'] }}"
