name: deploy
on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Enter text "destroy" to destroy selected environments'
        type: string
        default: ''
        required: false
      dev:
        description: 'Deploy Dev'
        type: boolean
        default: false
        required: false
      beta:
        description: 'Deploy beta'
        type: boolean
        default: false
        required: false
      preprod:
        description: 'Deploy preprod'
        type: boolean
        default: false
        required: false
      perf:
        description: 'Deploy perf'
        type: boolean
        default: false
        required: false
      production:
        description: 'Deploy production'
        type: boolean
        default: false
        required: false      
jobs:
  build: 
    uses: ./.github/workflows/template-build.yaml
    with:
    # for the testing purpose
      destroy: false
      # destroy: ${{ github.event.inputs.destroy }}
   
  plan-dev:
    needs: build
    if: ${{ inputs.dev == true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: dev
      
  deploy-dev:
    needs: plan-dev
    if: ${{ inputs.dev == true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: dev
  
  plan-beta:
    needs: build
    if: ${{ inputs.beta == true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: beta

  deploy-beta:
    needs: plan-beta
    if: ${{ inputs.beta == true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: beta



