name: deploy
on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the resources'
        type: boolean
        default: false
        required: false
      dev:
        description: 'Deploy Dev'
        type: boolean
        default: false
        required: false
      beta:
        description: 'Deploy beta'
        type: boolean
        default: false
        required: false
      preprod:
        description: 'Deploy preprod'
        type: boolean
        default: false
        required: false
      perf:
        description: 'Deploy perf'
        type: boolean
        default: false
        required: false
      production:
        description: 'Deploy production'
        type: boolean
        default: false
        required: false      
jobs:
  build: 
    uses: ./.github/workflows/template-build.yaml
    with:
    # for the testing purpose
      destroy: false
      # destroy: ${{ github.event.inputs.destroy }}
   
  deploy-dev:
    needs: build
    if: ${{ inputs.dev === true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environments: dev

  deploy-beta:
    needs: build
    if: ${{ inputs.beta === true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environments: beta

  deploy-preprod:
    needs: build
    if: ${{ inputs.preprod === true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environments: preprod

  deploy-perf:
    needs: build
    if: ${{ inputs.perf === true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environments: perf

  deploy-production:
    needs: build
    if: ${{ inputs.production === true }}
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environments: production


