name: deploy
on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the resources'
        type: boolean
        default: false
        required: false
      dev:
        description: 'Deploy Dev'
        type: boolean
        default: false
        required: false
      beta:
        description: 'Deploy beta'
        type: boolean
        default: false
        required: false
      preprod:
        description: 'Deploy preprod'
        type: boolean
        default: false
        required: false
      perf:
        description: 'Deploy perf'
        type: boolean
        default: false
        required: false
      production:
        description: 'Deploy production'
        type: boolean
        default: false
        required: false      
jobs:
  Build: 
    uses: ./.github/workflows/template-build.yaml
    with:
    # for the testing purpose
      destroy: false
      # destroy: ${{ github.event.inputs.destroy }}

  Deploy:
    needs: Build
    strategy:
      matrix:
        env: ['dev', 'beta', 'preprod', 'perf', 'prod']
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        if: ${{ matrix.env == 'dev' && inputs.dev == 'true' }}
        uses: ./.github/workflows/template-deploy.yaml
        with:
          environments: inputs.${{ matrix.env }}

      - name: Deploy to beta
        if: ${{ matrix.env == 'beta' && inputs.beta == 'true' }}
        uses: ./.github/workflows/template-deploy.yaml
        with:
          environments: inputs.${{ matrix.env }}

      - name: Deploy to preprod
        if: ${{ matrix.env == 'preprod' && inputs.preprod == 'true' }}
        uses: ./.github/workflows/template-deploy.yaml
        with:
          environments: inputs.${{ matrix.env }}

      - name: Deploy to perf
        if: ${{ matrix.env == 'perf' && inputs.perf == 'true' }}
        uses: ./.github/workflows/template-deploy.yaml
        with:
          environments: inputs.${{ matrix.env }}

      - name: Deploy to production
        if: ${{ matrix.env == 'production' && inputs.production == 'true' }}
        uses: ./.github/workflows/template-deploy.yaml
        with:
          environments: inputs.${{ matrix.env }}
