name: Deploy Workflow
on:
  workflow_call:
    inputs:
      destroy:
        required: false
        type: string
      ENVIRONMENT:
        required: true
        type: string

env: 
  terraformStateKey: main.terraform.${{ inputs.environments }}.tfstate
  terraformPlanKey: ${{ github.run_id }}.${{ github.run_attempt }}.main.${{ inputs.environments }}.tfplan

jobs:
  Plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Plan_${{inputs.environments}} 
        run:  echo '${{env.terraformStateKey}}----${{env.terraformPlanKey}}'
      - name: Plan_${{inputs.environments}} 
        run:  echo '${{toJson(github)}}'   
