name: Deploy Workflow
on:
  workflow_call:
    inputs:
      environments:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print environments
        run: echo "${{  inputs.environments }}"
